name: study-buddy
services:
  postgres:
    container_name: postgres (keycloak)
    image: postgres:15
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1
    command:
      - "start-dev"
    ports:
      - "9090:8080"
    environment:
      KC_DB_URL_HOST: postgres
      KC_DB_SCHEMA: public
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_LOGLEVEL: ALL
      KEYCLOAK_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 9090
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local