spring:
  application:
    name: user-service
server:
  port: 8083
clients:
  token-service:
    url: http://localhost:8082
  keycloak:
    url: http://localhost:9090
    realm: sekai
    client: niigo
    admin:
      username: miku
      password: miku
